name: Deploy Developer HostPool to NIH Environment

on:
  # for running manually  
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose environment to deploy
        options: 
        - Test
        - Prod
      hostpool_type:
        type: choice
        description: Choose hostpool type
        options: 
        - Pooled
        - Personal
        default: 'Pooled'
      deployment_stack_name: 
        type: string
        description: Name of deployment stack to delete
        default: 'Test-DevHostPool-Stack'
      update_existing_stack: 
        type: boolean
        description: Update existing stack if it exists
        default: false
  
  # for running as part of a workflow_call
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deployment_stack_name:
        required: true
        type: string
      update_existing_stack: 
        type: boolean
        description: Update existing stack if it exists
        default: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    # env:
    #   SESSION_HOST_PREFIX: ${{ inputs.environment == 'Prod' && 'avddhpp' || 'avddhpt' }}

    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        enable-AzPSSession: true

    - name: Test deploy deployment stack ${{ inputs.environment }} environment
      uses: azure/powershell@v2
      with:
        inlineScript: ./.github/workflows/scripts/DeploymentStack-DeveloperHostPool.ps1 -DeploymentStackName ${{ inputs.deployment_stack_name }} -Location 'eastus2' -TemplateFile './workload/bicep/deploy-baseline-developer-hostpool-arpah.bicep' -ParametersFile './workload/bicep/parameters/deploy-baseline-developer-hostpool-arpah.parameters.json' `
          -deploymentEnvironment ${{ inputs.environment }} -avdWorkloadSubsId ${{ secrets.AZURE_SUB_ID }} -avdEnterpriseAppObjectId ${{ secrets.AZURE_AVD_OBJECTID }} ` 
          -existingVnetPrivateEndpointSubnetResourceId ${{ secrets.AVD_SUBNET_ID }} -securityPrincipalId "${{ secrets.DEVELOPER_SECURITY_PRINCIPAL_ID }}" -update_existing_stack ${{ inputs.update_existing_stack }} `
          -avdHostPoolType '${{ inputs.hostpool_type }}'
        azPSVersion: "latest"
        errorActionPreference: stop

    # - name: Update AVD Application Group Display Name in the ${{ inputs.environment }} environment
    #   uses: azure/powershell@v2
    #   env:
    #     ResourceGroupName: 'avd-nih-arpah-${{ inputs.environment }}-use2-service-objects'
    #     ApplicationGroupName: 'vdag-desktop-developer-${{ inputs.environment }}-use2-001'
    #     Name: 'SessionDesktop'
    #     FriendlyName: 'ARPA-H Windows Developer'
    #   with:
    #     inlineScript: ./.github/workflows/scripts/update_app_display_name.ps1 -ResourceGroupName ${{ env.ResourceGroupName }} -ApplicationGroupName  ${{ env.ApplicationGroupName }} -Name  ${{ env.Name }} -FriendlyName  '${{ env.FriendlyName }}'
    #     azPSVersion: "latest"
    #     errorActionPreference: continue

    - name: Update AVD Application Group Display Name in the ${{ inputs.environment }} environment
      uses: azure/powershell@v2
      env:
        ResourceGroupName: 'avd-nih-arpah-${{ inputs.environment }}-use2-service-objects'
        ApplicationGroupName: 'vdag-desktop-developer-${{ inputs.hostpool_type }}-${{ inputs.environment }}-use2-001'
        # TEST:                 'vdag-desktop-${toLower(hostPoolPersona)}--${toLower(avdHostPoolType)}-${toLower(deploymentEnvironment)}-use2-001'
        Name: 'SessionDesktop'
        FriendlyName: 'ARPA-H Windows Developer '
      with:
        inlineScript: ./.github/workflows/scripts/update_app_display_name.ps1 -ResourceGroupName ${{ env.ResourceGroupName }} -ApplicationGroupName  ${{ env.ApplicationGroupName }} -Name  ${{ env.Name }} -FriendlyName  '${{ env.FriendlyName }}'
        azPSVersion: "latest"
        errorActionPreference: continue