name: Deploy Developer AVD to NIH Environment

on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          description: Choose environment to deploy
          options: 
          - Test
          - Prod
        deployment_stack_name: 
          type: string
          description: Name of deployment stack to delete
          default: 'Test-DevHostPool-Stack'
jobs:
  deploy-developer-hostpool:
    name: deploy developer hostpool
    uses: ./.github/workflows/Deploy-Developer-HostPool.yml
    with:
      environment: ${{ inputs.environment }}
      deployment_stack_name: '${{ inputs.deployment_stack_name }}-HostPool'
    secrets: inherit
  
  deploy-developer-sessionhosts:
    name: deploy developer sessionhosts
    uses: ./.github/workflows/Deploy-Developer-SessionHosts.yml
    with:
      environment: ${{ inputs.environment }}
      deployment_stack_name: '${{ inputs.deployment_stack_name }}-SessionHosts'
    secrets: inherit