name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUB_ID }}
        region: eastus2
        resourceGroupName: ${{ secrets.AVD01_AZURE_RG }}
        template: ./workload/bicep/deploy-baseline.bicep
        parameters: ./workload/bicep/deploy-baseline.bicepparam avdWorkloadSubsId=${{ secrets.AZURE_SUB_ID }} avdVmLocalUserPassword=${{ secrets.AVD01_LOCAL_ADMINPWD }}
        failOnStdErr: false
