name: Deploy to NIH Prod

on:
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBID_PROD }}
        region: eastus
        template: ./workload/bicep/deploy-baseline-arpah.bicep
        parameters: ./workload/bicep/parameters/deploy-baseline-parameters-arpah.json deploymentEnvironment=Prod avdWorkloadSubsId=${{ secrets.AZURE_SUBID_PROD }} avdVmLocalUserName=${{ secrets.AVD_ADMIN }} avdVmLocalUserPassword=${{ secrets.AVD_ADMINPASS }} avdEnterpriseAppObjectId=${{ secrets.AZURE_AVD_OBJECTID }} existingVnetAvdSubnetResourceId=${{ secrets.AZURE_VPCSUBID_PROD }} existingVnetPrivateEndpointSubnetResourceId=${{ secrets.AZURE_VPCSUBID_PROD }} identityDomainName=${{ secrets.AD_NAME}} avdDomainJoinUserName=${{ secrets.AD_JOIN_USER }} avdDomainJoinUserPassword=${{ secrets.AD_JOIN_PASS }} avdOuPath="${{ secrets.AD_OU_PROD }}" storageOuPath="${{ secrets.AD_OU_PROD }}"
        failOnStdErr: false
    
    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v2
      with:
        inlineScript: ./.github/workflows/scripts/update_app_display_name.ps1 -ResourceGroupName 'avd-nih-arpah-prod-use2-service-objects' -ApplicationGroupName 'vdag-desktop-app1-prod-use2-001' -Name 'SessionDesktop' -FriendlyName ' Windows 11 Desktop'
        azPSVersion: "latest"
        errorActionPreference: continue