name: Deploy Bicep file

on:
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: eastus
        template: ./workload/bicep/deploy-baseline-arpah.bicep
        parameters: ./workload/bicep/parameters/deploy-baseline-parameters-arpah.json avdWorkloadSubsId=${{ secrets.AZURE_SUBID_TEST}} deploymentPrefix=AVDN avdVmLocalUserName=${{ secrets.AVD_ADMIN }} avdVmLocalUserPassword=${{ secrets.AVD_ADMINPASS }} avdIdentityServiceProvider=EntraID avdEnterpriseAppObjectId=${{ secrets.AZURE_AVD_OBJECTID }} avdDeployMonitoring=true createAvdVnet=false createAvdFslogixDeployment=true deployAlaWorkspace=true avdSessionHostLocation=eastus2 avdManagementPlaneLocation=eastus2 existingVnetAvdSubnetResourceId=${{ secrets.AZURE_VPCSUBID_TEST }} existingVnetPrivateEndpointSubnetResourceId=${{ secrets.AZURE_VPCSUBID_TEST }} deployPrivateEndpointKeyvaultStorage=true createPrivateDnsZones=true
        failOnStdErr: false
