name: Deploy Using Deployment Stack

on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          description: Choose environment to deploy
          options: 
          - Test
          - Prod
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        enable-AzPSSession: true

    # - name: Azure CLI script
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: latest
    #     inlineScript: |
    #       az stack sub create --name 'Test-Depl-Statck' --location 'eastus2' --template-file './workload/bicep/test/deploy-stack.bicep' --parameters './workload/bicep/test/deploy-stack.parameters' --action-on-unmanage 'detachAll' --deny-settings-mode 'none'

    # - name: Deploy Bicep file to ${{ github.event.inputs.environment }} environment
    #   uses: azure/arm-deploy@v2
    #   with:
    #     scope: subscription
    #     subscriptionId: ${{ secrets.AZURE_SUB_ID }}
    #     region: eastus2
    #     #deploymentMode: 'Validate'
    #     template: ./workload/bicep/deploy-baseline-arpah.bicep
    #     parameters: ./workload/bicep/parameters/deploy-baseline-developer-arpah.parameters.json deploymentEnvironment=${{ github.event.inputs.environment }} avdWorkloadSubsId=${{ secrets.AZURE_SUB_ID }} imageGallerySubscriptionId=${{ secrets.IMAGE_GALLERY_SUB_ID }} avdVmLocalUserName=${{ secrets.AVD_ADMIN }} avdVmLocalUserPassword=${{ secrets.AVD_ADMINPASS }} avdEnterpriseAppObjectId=${{ secrets.AZURE_AVD_OBJECTID }} existingVnetAvdSubnetResourceId=${{ secrets.AVD_SUBNET_ID }} existingVnetPrivateEndpointSubnetResourceId=${{ secrets.AVD_SUBNET_ID }} identityDomainName=${{ secrets.AD_NAME}} avdDomainJoinUserName=${{ secrets.AD_JOIN_USER }} avdDomainJoinUserPassword=${{ secrets.AD_JOIN_PASS }} avdOuPath="${{ secrets.AD_OU }}" storageOuPath="${{ secrets.AD_OU }}" storageFilePrivateEndpointStaticIp="${{ secrets.STORAGEFILEPRIVATEENDPOINTSTATICIP }}" securityPrincipalId="${{ secrets.SECURITY_PRINCIPAL_ID }}" securityPrincipalName="${{ secrets.SECURITY_PRINCIPAL_NAME }}" avdVnetPrivateDnsZoneFilesId= avdVnetPrivateDnsZoneKeyvaultId=
    #     failOnStdErr: false

    - name: Test deploy deployment stack ${{ github.event.inputs.environment }} environment
      uses: azure/powershell@v2
      # env:
        # ResourceGroupName: 'avd-nih-arpah-developer-${{ github.event.inputs.environment }}-use2-service-objects'
        # ApplicationGroupName: 'vdag-desktop-developer-${{ github.event.inputs.environment }}-use2-001'
        # Name: 'SessionDesktop'
        # FriendlyName: 'ARPA-H Developer Windows Desktop'
      with:
        inlineScript: ./.github/workflows/scripts/DeploymentStack.ps1 -subscriptionId ${{ secrets.AZURE_SUB_ID }} -DeploymentStackName 'Test-Depl-Stack' -Location 'eastus2' -TemplateFile './workload/bicep/test/deploy-stack.bicep' -ParametersFile './workload/bicep/test/deploy-stack.parameters.json'
        azPSVersion: "latest"
        errorActionPreference: stop
