name: Deploy Developer Session Hosts to NIH Environment

on:
  # for running manually  
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose environment to deploy
        options: 
        - Test
        - Prod
      hostpool_type:
        type: choice
        description: Choose hostpool type
        options: 
        - Pooled
        - Personal
        default: 'Pooled'
      session_host_count: 
        type: number
        description: Number of session hosts
        default: '1'
      deployment_stack_name: 
        type: string
        description: Name of deployment stack to delete
        default: 'Test-DevSessionHosts-Stack'
      update_existing_stack: 
        type: boolean
        description: Update existing stack if it exists
        default: false
  
  # for running as part of a workflow_call
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deployment_stack_name:
        required: true
        type: string
      update_existing_stack: 
        type: boolean
        description: Update existing stack if it exists
        default: false

jobs:
  generate-hostpool-token:
    name: deploy developer hostpool
    uses: ./.github/workflows/Generate-HostPoolToken.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      SESSION_HOST_PREFIX: ${{ inputs.environment == 'Prod' && 'avddevp' || 'avddevt' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        enable-AzPSSession: true

    - name: Test deploy deployment stack ${{ inputs.environment }} environment
      uses: azure/powershell@v2
      with:
        inlineScript: ./.github/workflows/scripts/DeploymentStack-DeveloperSessionHost.ps1 -DeploymentStackName ${{ inputs.deployment_stack_name }} -Location 'eastus2' -TemplateFile './workload/bicep/deploy-baseline-developer-sessionhosts-arpah.bicep' -ParametersFile './workload/bicep/parameters/deploy-baseline-developer-sessionhost-arpah.parameters.json' `
          -avdSessionHostCustomNamePrefix ${{ env.SESSION_HOST_PREFIX }} -deploymentEnvironment ${{ inputs.environment }} -avdWorkloadSubsId ${{ secrets.AZURE_SUB_ID }} -imageGallerySubscriptionId ${{ secrets.IMAGE_GALLERY_SUB_ID }} ` 
          -existingVnetAvdSubnetResourceId ${{ secrets.AVD_DEVELOPER_SUBNET_ID }} -existingVnetPrivateEndpointSubnetResourceId ${{ secrets.AVD_SUBNET_ID }} -identityDomainName ${{ secrets.AD_NAME}} -avdOuPath "${{ secrets.AD_OU }}" -securityPrincipalId "${{ secrets.DEVELOPER_SECURITY_PRINCIPAL_ID }}" ` 
          -update_existing_stack ${{ inputs.update_existing_stack }} -avdHostPoolType '${{ inputs.hostpool_type }}' -avdDeploySessionHostsCount ${{ inputs.session_host_count }}
        azPSVersion: "latest"
        errorActionPreference: stop
