name: Deploy Developer AVD to NIH Environment

on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          description: Choose environment to deploy
          options: 
          - Test
          - Prod
        deployment_stack_name: 
          type: string
          description: Name of deployment stack to delete
          default: 'Test-DevHostPool-Stack'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      SESSION_HOST_PREFIX: ${{ github.event.inputs.environment == 'Prod' && 'avddhpp' || 'avddhpt' }}

    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        enable-AzPSSession: true

    # - name: Deploy Bicep file to ${{ github.event.inputs.environment }} environment
    #   uses: azure/arm-deploy@v2
    #   with:
    #     scope: subscription
    #     subscriptionId: ${{ secrets.AZURE_SUB_ID }}
    #     region: eastus2
    #     #deploymentMode: 'Validate'
    #     template: ./workload/bicep/deploy-baseline-developer-arpah.bicep
    #     parameters: ./workload/bicep/parameters/deploy-baseline-developer-arpah.parameters.json deploymentEnvironment=${{ github.event.inputs.environment }} avdWorkloadSubsId=${{ secrets.AZURE_SUB_ID }} imageGallerySubscriptionId=${{ secrets.IMAGE_GALLERY_SUB_ID }} avdVmLocalUserName=${{ secrets.AVD_ADMIN }} avdVmLocalUserPassword=${{ secrets.AVD_ADMINPASS }} avdEnterpriseAppObjectId=${{ secrets.AZURE_AVD_OBJECTID }} existingVnetAvdSubnetResourceId=${{ secrets.AVD_SUBNET_ID }} existingVnetPrivateEndpointSubnetResourceId=${{ secrets.AVD_SUBNET_ID }} identityDomainName=${{ secrets.AD_NAME}} avdDomainJoinUserName=${{ secrets.AD_JOIN_USER }} avdDomainJoinUserPassword=${{ secrets.AD_JOIN_PASS }} avdOuPath="${{ secrets.AD_OU }}" storageOuPath="${{ secrets.AD_OU }}" storageFilePrivateEndpointStaticIp="${{ secrets.STORAGEFILEPRIVATEENDPOINTSTATICIP }}" securityPrincipalId="${{ secrets.SECURITY_PRINCIPAL_ID }}" securityPrincipalName="${{ secrets.SECURITY_PRINCIPAL_NAME }}" avdVnetPrivateDnsZoneFilesId= avdVnetPrivateDnsZoneKeyvaultId=
    #     failOnStdErr: false

    - name: Test deploy deployment stack ${{ github.event.inputs.environment }} environment
      uses: azure/powershell@v2
      with:
        inlineScript: ./.github/workflows/scripts/DeploymentStack-DeveloperHostPool.ps1 -DeploymentStackName ${{ github.event.inputs.deployment_stack_name }} -Location 'eastus2' -TemplateFile './workload/bicep/deploy-baseline-developer-arpah.bicep' -ParametersFile './workload/bicep/parameters/deploy-baseline-developer-arpah.parameters.json' `
          avdSessionHostCustomNamePrefix=${{ env.SESSION_HOST_PREFIX }} deploymentEnvironment=${{ github.event.inputs.environment }} avdWorkloadSubsId=${{ secrets.AZURE_SUB_ID }} imageGallerySubscriptionId=${{ secrets.IMAGE_GALLERY_SUB_ID }} avdEnterpriseAppObjectId=${{ secrets.AZURE_AVD_OBJECTID }} ` 
          existingVnetAvdSubnetResourceId=${{ secrets.AVD_SUBNET_ID }} existingVnetPrivateEndpointSubnetResourceId=${{ secrets.AVD_SUBNET_ID }} identityDomainName=${{ secrets.AD_NAME}} avdOuPath="${{ secrets.AD_OU }}" ` 
          securityPrincipalId="${{ secrets.SECURITY_PRINCIPAL_ID }}"
        azPSVersion: "latest"
        errorActionPreference: stop

    # - name: Update AVD Application Group Display Name in the ${{ github.event.inputs.environment }} environment
    #   uses: azure/powershell@v2
    #   env:
    #     ResourceGroupName: 'avd-nih-arpah-developer-${{ github.event.inputs.environment }}-use2-service-objects'
    #     ApplicationGroupName: 'vdag-desktop-developer-${{ github.event.inputs.environment }}-use2-001'
    #     Name: 'SessionDesktop'
    #     FriendlyName: 'ARPA-H Developer Windows Desktop'
    #   with:
    #     inlineScript: ./.github/workflows/scripts/update_app_display_name.ps1 -ResourceGroupName ${{ env.ResourceGroupName }} -ApplicationGroupName  ${{ env.ApplicationGroupName }} -Name  ${{ env.Name }} -FriendlyName  '${{ env.FriendlyName }}'
    #     azPSVersion: "latest"
    #     errorActionPreference: continue
